### ISSUE TITLE
Updates required to run date-picker sample

### ISSUE THREAD

**Issue by BrianJVarley** [smooch/conversation-extension-examples#13]
@alavers  noticed the following needs to be updated to run the sample.

Change `scope: 'account to '`scope: 'app'` - see: https://github.com/smooch/smooch-desk/issues/41#issuecomment-376548058

https://github.com/smooch/conversation-extension-examples/blob/master/datepicker-react/server/app.js#L18

In Step 5 of README - change command to `npm run dev`:
https://github.com/smooch/conversation-extension-examples/blob/master/datepicker-react/server/app.js#L18

**Comment by alavers** [comment]
Thanks @BrianJVarley I'll take a look
